version: '3.8'

services:
	# PostgreSQL Database Container
	db:
		image: postgres:15
		container_name: postgres-db
		environment:
			POSTGRES_DB: tododb
			POSTGRES_USER: postgres
			POSTGRES_PASSWORD: postgres
		ports:
			- "5432:5432"
		volumes:
			- postgres-data:/var/lib/postgresql/data
		networks:
			- todolist-network
			
	# Spring Boot Application Container
	todolist:
		build:
			context: .
			dockerfile: Dockerfile
		container_name: todolist
		environment:
			SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tododb
			SPRING_DATASOURCE_USERNAME: postgres
			SPRING_DATASOURCE_PASSWORD: postgres
		ports:
			- "8080:8080"
		depends_on:
			- db
		networks:
			- todolist-network
			
	volumes:
		postgres-data
		
	networks:
		todolist-network:
			driver: bridge